version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["python", "app.py"]
    depends_on:
      - db
    networks:
      - app-network

  
  dance-studio-website:
    build:
      context: ./dance-studio-website
    container_name: dance-studio-website
    restart: unless-stopped
    ports:
      - "3001:5173"
    volumes:
      - ./dance-studio-website:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - app-network
  # MySQL (Database)
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  
      
networks:
  app-network:
    driver: bridge